apiVersion: v1
kind: Secret
metadata:
  name: patentiq-secrets
type: Opaque
stringData:
  db-password: "super_secure_pg_pass"
  neo4j-password: "super_secure_graph_pass"
  jwt-secret: "enterprise-grade-jwt-secret-key-32bytes+"
  stripe-secret: "sk_test_mock_stripe_key"
  openai-key: "sk-mock-openai-key"
